# Generated by Django 2.0.1 on 2018-04-05 14:12

import apps.investment.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_core', '0035_auto_20180328_1436'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid'), ('consumed', 'consumed'), ('cancelled', 'cancelled')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('code', models.CharField(default=apps.investment.models.gen_code, max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_chages', to='exchange_core.Accounts')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.CreateModel(
            name='GracePeriods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('months', models.IntegerField(unique=True, verbose_name='Months')),
            ],
            options={
                'verbose_name': 'Grace period',
                'verbose_name_plural': 'Grace periods',
            },
        ),
        migrations.CreateModel(
            name='Graduations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('promoter', 'Investment Promoter'), ('advisor', 'Investment Advisor')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoreIncomeDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Date to be ignored')),
            ],
            options={
                'verbose_name': 'Ignore income date',
                'verbose_name_plural': 'Ignore income dates',
            },
        ),
        migrations.CreateModel(
            name='PlanGracePeriods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_income', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Daily income percent')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_grace_periods', to='exchange_core.Currencies', verbose_name='Currency')),
                ('grace_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='investment.GracePeriods')),
            ],
            options={
                'verbose_name': 'Plan grace period',
                'verbose_name_plural': 'Plan grace periods',
                'ordering': ['grace_period__months'],
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_down', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Min down')),
                ('max_down', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Max down')),
                ('membership_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Membership fee')),
                ('allow_monthly_draw', models.BooleanField(default=True, verbose_name='Allow monthly draw')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plangraceperiods',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='investment.Plans'),
        ),
        migrations.AddField(
            model_name='charges',
            name='plan_grace_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='investment.PlanGracePeriods', verbose_name='Plan grace period'),
        ),
        migrations.AlterUniqueTogether(
            name='plangraceperiods',
            unique_together={('plan', 'grace_period', 'currency')},
        ),
    ]
