# Generated by Django 2.2.8 on 2019-12-04 01:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GracePeriods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('months', models.IntegerField(unique=True, verbose_name='Months')),
            ],
            options={
                'verbose_name': 'Grace period',
                'verbose_name_plural': 'Grace periods',
            },
        ),
        migrations.CreateModel(
            name='IgnoreIncomeDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Date to be ignored')),
            ],
            options={
                'verbose_name': 'Ignore income date',
                'verbose_name_plural': 'Ignore income dates',
            },
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('membership_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Membership Fee')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Paid Date')),
                ('status', models.CharField(choices=[('paid', 'paid'), ('consumed', 'consumed'), ('cancelled', 'cancelled')], default='paid', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='exchange_core.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
            },
        ),
        migrations.CreateModel(
            name='PlanGracePeriods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Income percent')),
                ('payment_type', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly')], default='monthly', max_length=20, verbose_name='Payment Type')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_grace_periods', to='exchange_core.Currencies', verbose_name='Currency')),
                ('grace_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='investment.GracePeriods', verbose_name='Grace Period')),
            ],
            options={
                'verbose_name': 'Plan grace period',
                'verbose_name_plural': 'Plan grace periods',
                'ordering': ['grace_period__months'],
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_down', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Min down')),
                ('max_down', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Max down')),
                ('min_reinvest', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min reinvest')),
                ('membership_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Membership Fee')),
                ('promoter_comission', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Promoter Comission')),
                ('advisor_comission', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Advisor Comission')),
                ('allow_monthly_draw', models.BooleanField(default=True, verbose_name='Allow monthly draw')),
                ('order', models.IntegerField(default=0)),
                ('overdraft_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Overdraft Percent')),
                ('overdraft_interest_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Overdraft interest percent')),
                ('overdraft_free_days', models.IntegerField(default=0, verbose_name='Overdraft Free Days')),
                ('loan_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Loan Percent')),
                ('loan_interest_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Loan interest percent')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Reinvestments',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_before', models.DecimalField(decimal_places=8, max_digits=20)),
                ('incomes', models.DecimalField(decimal_places=8, max_digits=20)),
                ('membership_fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('consumed', 'consumed')], default='paid', max_length=30)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinvestments', to='investment.Investments')),
                ('new_invest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_invests', to='investment.PlanGracePeriods')),
                ('old_invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_invests', to='investment.PlanGracePeriods')),
            ],
            options={
                'verbose_name': 'Reinvestment',
                'verbose_name_plural': 'Reinvestments',
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plangraceperiods',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='investment.Plans', verbose_name='Plan'),
        ),
        migrations.CreateModel(
            name='Overdrafts',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrowed_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('interest_percent', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='exchange_core.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrowed_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('times', models.IntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='exchange_core.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.AddField(
            model_name='investments',
            name='plan_grace_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment.PlanGracePeriods', verbose_name='Plan grace period'),
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('due_date', models.DateField()),
                ('interest_percent', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='investment.Loans', verbose_name='Statement')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comissions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fk', models.UUIDField(null=True)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Investments')),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Referrals')),
                ('reinvestment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Reinvestments')),
            ],
            options={
                'verbose_name': 'Comission',
                'verbose_name_plural': 'Comissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='plangraceperiods',
            unique_together={('plan', 'grace_period', 'currency')},
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='created', max_length=30)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='investment.Investments')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'unique_together': {('investment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Graduations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('promoter', 'Investment Promoter'), ('advisor', 'Investment Advisor')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduation',
                'verbose_name_plural': 'Graduations',
                'unique_together': {('user', 'type')},
            },
        ),
    ]
