# Generated by Django 2.0.1 on 2018-05-09 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20180509_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='membership_fee',
        ),
        migrations.AddField(
            model_name='plans',
            name='min_reinvest',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min reinvest'),
        ),
    ]
