# Generated by Django 2.0.1 on 2018-05-20 15:13

import apps.investment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0035_auto_20180328_1436'),
        ('investment', '0005_incomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid'), ('consumed', 'consumed'), ('cancelled', 'cancelled')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('code', models.CharField(default=apps.investment.models.gen_code, max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_chages', to='exchange_core.Accounts')),
                ('plan_grace_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment.PlanGracePeriods', verbose_name='Plan grace period')),
            ],
            options={
                'verbose_name': 'User Investment',
                'verbose_name_plural': 'Users Investment',
            },
        ),
        migrations.RemoveField(
            model_name='charges',
            name='account',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='plan_grace_period',
        ),
        migrations.RemoveField(
            model_name='incomes',
            name='charge',
        ),
        migrations.DeleteModel(
            name='Charges',
        ),
        migrations.AddField(
            model_name='incomes',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='investment.Investments'),
        ),
    ]
