# Generated by Django 2.0.1 on 2018-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_auto_20180520_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investments',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
    ]
