# Generated by Django 2.0.1 on 2018-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_remove_investments_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_chages', to='exchange_core.Accounts', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid Date'),
        ),
        migrations.AlterField(
            model_name='plangraceperiods',
            name='grace_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='investment.GracePeriods', verbose_name='Grace Period'),
        ),
        migrations.AlterField(
            model_name='plangraceperiods',
            name='payment_type',
            field=models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly')], default='monthly', max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='plangraceperiods',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='investment.Plans', verbose_name='Plan'),
        ),
    ]
