# Generated by Django 2.0.1 on 2018-05-20 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0009_auto_20180520_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduations',
            unique_together={('user', 'type')},
        ),
    ]
