# Generated by Django 2.0.1 on 2018-05-25 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_auto_20180520_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='membership_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Membership Fee'),
        ),
    ]
