# Generated by Django 2.0.1 on 2018-05-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_auto_20180526_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='exchange_core.Accounts', verbose_name='Account'),
        ),
    ]
