# Generated by Django 2.0.1 on 2018-05-30 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_auto_20180530_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Plans')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Referrals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
