# Generated by Django 2.0.1 on 2018-05-31 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_comissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissions',
            name='graduation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Graduations'),
        ),
    ]
