# Generated by Django 2.0.1 on 2018-05-31 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_comissions_graduation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissions',
            name='graduation',
        ),
    ]
