# Generated by Django 2.0.1 on 2018-06-06 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_auto_20180605_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='advisor_comission',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Advisor Comission'),
        ),
        migrations.AddField(
            model_name='plans',
            name='promoter_comission',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Promoter Comission'),
        ),
    ]
