# Generated by Django 2.0.1 on 2018-06-11 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0021_remove_comissions_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinvestments',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_before', models.DecimalField(decimal_places=8, max_digits=20)),
                ('incomes', models.DecimalField(decimal_places=8, max_digits=20)),
                ('membership_fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('new_invest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_invests', to='investment.PlanGracePeriods')),
                ('old_invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_invests', to='investment.PlanGracePeriods')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
