# Generated by Django 2.0.1 on 2018-06-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_reinvestments'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinvestments',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinvestments', to='investment.Investments'),
        ),
    ]
