# Generated by Django 2.0.6 on 2018-06-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0023_reinvestments_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissions',
            name='reinvestment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Reinvestments'),
        ),
    ]
