# Generated by Django 2.0.1 on 2018-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0025_auto_20180625_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='status',
            field=models.CharField(default='created', max_length=30),
        ),
    ]
