# Generated by Django 2.0.1 on 2018-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_incomes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissions',
            name='fk',
            field=models.UUIDField(null=True),
        ),
    ]
