# Generated by Django 2.0.1 on 2018-07-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0027_comissions_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissions',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='investment.Referrals'),
        ),
    ]
