# Generated by Django 2.0.1 on 2018-07-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0028_auto_20180703_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissions',
            options={'verbose_name': 'Comission', 'verbose_name_plural': 'Comissions'},
        ),
        migrations.AlterModelOptions(
            name='reinvestments',
            options={'verbose_name': 'Reinvestment', 'verbose_name_plural': 'Reinvestments'},
        ),
    ]
