# Generated by Django 2.0.1 on 2018-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0029_auto_20180704_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinvestments',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('consumed', 'consumed')], default='paid', max_length=30),
        ),
    ]
