# Generated by Django 2.1 on 2018-08-21 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0030_reinvestments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='credit_interest_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Credit interest percent'),
        ),
        migrations.AddField(
            model_name='plans',
            name='credit_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Credit Percent'),
        ),
        migrations.AddField(
            model_name='plans',
            name='interest_free_days',
            field=models.IntegerField(default=0, verbose_name='Interest Free Days'),
        ),
        migrations.AddField(
            model_name='plans',
            name='loan_interest_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Loan interest percent'),
        ),
        migrations.AddField(
            model_name='plans',
            name='loan_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Loan Percent'),
        ),
    ]
