# Generated by Django 2.1 on 2018-08-21 02:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0031_auto_20180821_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='credit_interest_percent',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='credit_percent',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='interest_free_days',
        ),
        migrations.AddField(
            model_name='plans',
            name='overdraft_free_days',
            field=models.IntegerField(default=0, verbose_name='Overdraft Free Days'),
        ),
        migrations.AddField(
            model_name='plans',
            name='overdraft_interest_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Overdraft interest percent'),
        ),
        migrations.AddField(
            model_name='plans',
            name='overdraft_percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Overdraft Percent'),
        ),
    ]
