# Generated by Django 2.1 on 2018-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180810_1906'),
        ('investment', '0032_auto_20180821_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Overdrafts',
        ),
    ]
