# Generated by Django 2.2.8 on 2019-12-04 01:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Number')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('document_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Document 1')),
                ('document_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Document 2')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers name')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fathers name')),
                ('deposit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Deposit')),
                ('reserved', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Reserved')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='exchange_core.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Recharges',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('quote', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Quote')),
                ('deposit', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Deposit in the moment')),
                ('reserved', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Reserved in the moment')),
                ('is_paid', models.BooleanField(default=False, help_text='Mark this if the rechard has been paid', verbose_name='Is paid')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='card.Cards')),
            ],
            options={
                'verbose_name': 'Recharge',
                'verbose_name_plural': 'Recharges',
            },
        ),
    ]
