# Generated by Django 2.0.1 on 2018-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20180719_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
