# Generated by Django 2.1 on 2018-08-08 18:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20180725_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharges',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('quote', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Quote')),
                ('deposit', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Deposit in the moment')),
                ('reserved', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Reserved in the moment')),
            ],
            options={
                'verbose_name': 'Recharge',
                'verbose_name_plural': 'Recharges',
            },
        ),
        migrations.AddField(
            model_name='cards',
            name='deposit',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Balance in the moment'),
        ),
        migrations.AddField(
            model_name='cards',
            name='reserved',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Balance in the moment'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='document_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='document_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recharges',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='card.Cards'),
        ),
    ]
