# Generated by Django 2.1 on 2018-08-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20180808_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharges',
            old_name='account',
            new_name='card',
        ),
    ]
