# Generated by Django 2.1 on 2018-08-10 19:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20180809_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='exchange_core.Accounts', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='deposit',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='document_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='document_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fathers name'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers name'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='reserved',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Reserved'),
        ),
    ]
