# Generated by Django 2.2.8 on 2019-12-04 01:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('expiration_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_document', models.CharField(max_length=20)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receipt')),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid')], default='created', max_length=15)),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
