# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('expiration_date', models.DateField()),
                ('payment_date', models.DateField(null=True)),
                ('checksum', models.CharField(max_length=1)),
                ('payer_name', models.CharField(max_length=20)),
                ('payer_document', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid')], default='created', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
