# Generated by Django 2.2.8 on 2019-12-04 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('boleto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='card.Cards'),
        ),
    ]
