# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Receipt'),
        ),
    ]
