# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 17:39
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0002_boletos_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='boletos',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
