# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0003_auto_20171130_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletos',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
