# Generated by Django 2.0.1 on 2018-05-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0004_auto_20171201_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletos',
            options={'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
    ]
