# Generated by Django 2.1 on 2018-08-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20180810_1906'),
        ('boleto', '0005_auto_20180509_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletos',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='user',
        ),
        migrations.AddField(
            model_name='boletos',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='card.Cards'),
        ),
    ]
