# Generated by Django 2.1 on 2018-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0006_auto_20180810_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletos',
            name='payer_name',
            field=models.CharField(max_length=100),
        ),
    ]
